### ISSUE TITLE
attr/attributes.h: No such file or directory

### ISSUE THREAD

**Issue by niXman** [legionus/osec#1]
Hi,

Ubuntu-20.04-x86_64.

when I try to build this project I got `dbvalue.c:244:10: fatal error: attr/attributes.h: No such file or directory` error.

which lib should I install too?

I have installed `libcap-dev` (POSIX 1003.1e capabilities).

thanks.

**Comment by legionus** [comment]
@niXman this header in the `libattr1-dev`.

**Comment by niXman** [comment]
thank you!

but can you please add this lib into list of [prereqs](https://github.com/legionus/osec#requires) ;)

**Comment by legionus** [comment]
Sure. I will.
